
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Environment Check 
      run: env

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++-11

    - name: Setup GoogleTest
      uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Build main application
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Run C++ tests
      run: |
        ./build.sh test
        ./tests  # Ensure this matches your test binary path

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python tests
      run: |
        python3 test/test_random.py 
